# Site settings
title: Agrippa Data Consultinng
email: info@agrippadataconsuling.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Agrippa Data Consulting
email: info@agrippadataconsuling.com
facebook_username:
twitter_username:
github_username: nltmickc
address:
  - line: The CHQ Building
  - line: Dublin 1
  - line: Ireland
telephone:
copyright:

# API settings
google_api_key: AIzaSyAOuKvxz8ZNOQOu_uq1QRB00ZP5SXf4S34

# Build settings
markdown: kramdown
